# First part of tensorflow developer course

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.0


create tensors with tf.Constant()

In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim # number of dimensions

0

In [ ]:
vector = tf.constant([5, 6])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[2,3], [4,5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
matrix_2 = tf.constant([[20, 3.],
                        [3, 4],
                        [3, 54]], dtype = tf.float16)

In [ ]:
matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[20.,  3.],
       [ 3.,  4.],
       [ 3., 54.]], dtype=float16)>

In [ ]:
matrix_2.ndim

2

In [ ]:
tensor = tf.constant([[[3,4,5],
                       [4, 5,6]],
                      [[3,4,5,],
                      [45,5,6]],
                      [[4,5,6],
                       [4,5,6]]])

In [ ]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 3,  4,  5],
        [ 4,  5,  6]],

       [[ 3,  4,  5],
        [45,  5,  6]],

       [[ 4,  5,  6],
        [ 4,  5,  6]]], dtype=int32)>

In [ ]:
tensor_2 = tf.Variable([10, 7])
tensor_2

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
tensor_2[0].assign(0)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([0, 7], dtype=int32)>

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
not_shuffled = tf.constant([[10, 4],
                            [2, 4]])

In [ ]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  4],
       [ 2,  4]], dtype=int32)>

In [ ]:
tf.ones(shape = (3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape = (3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
import numpy as np

In [ ]:
array_A = np.array([3,4,6,3,5,5,6,7,3,45,])

In [ ]:
array_A

array([ 3,  4,  6,  3,  5,  5,  6,  7,  3, 45])

In [ ]:
tensor_A = tf.constant(array_A)

In [ ]:
tensor_A.shape

TensorShape([10])

In [ ]:
tf.size(tensor_A)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
tensorB = tf.zeros(shape =[2,3,4,5])

In [ ]:
tensorB

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
tensorB.shape

TensorShape([2, 3, 4, 5])

In [ ]:
#tensorB.numpy()

In [ ]:
# Nnew axis
tensor_C = tensorB[..., tf.newaxis]

In [ ]:
#tf.expand_dims(tensorB, axis = 3)

In [ ]:
#tf.add(tensor_C, 20)

In [ ]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 3,  4,  5],
        [ 4,  5,  6]],

       [[ 3,  4,  5],
        [45,  5,  6]],

       [[ 4,  5,  6],
        [ 4,  5,  6]]], dtype=int32)>

In [ ]:
tf.transpose(tensor)

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 3,  3,  4],
        [ 4, 45,  4]],

       [[ 4,  4,  5],
        [ 5,  5,  5]],

       [[ 5,  5,  6],
        [ 6,  6,  6]]], dtype=int32)>

In [ ]:
X = tf.Variable([[5,6, 6], [3, 8,8]])

In [ ]:
X

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[5, 6, 6],
       [3, 8, 8]], dtype=int32)>

In [ ]:
y = tf.Variable([[3,4,], [3,8], [5,1]])

In [ ]:
y

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[3, 4],
       [3, 8],
       [5, 1]], dtype=int32)>

In [ ]:
tf.matmul(X, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[63, 74],
       [73, 84]], dtype=int32)>

In [ ]:
tf.tensordot(X, y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[63, 74],
       [73, 84]], dtype=int32)>

In [ ]:
tf.transpose(X)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 3],
       [6, 8],
       [6, 8]], dtype=int32)>

In [ ]:
D = tf.cast(X, dtype = tf.float16)

In [ ]:
D

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[5., 6., 6.],
       [3., 8., 8.]], dtype=float16)>

In [ ]:
tf.reduce_max(D)

<tf.Tensor: shape=(), dtype=float16, numpy=8.0>

In [ ]:
tf.reduce_mean(X)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [ ]:
tf.reduce_mean(D)

<tf.Tensor: shape=(), dtype=float16, numpy=6.0>

In [ ]:
import tensorflow_probability as tfp

In [ ]:
tfp.stats.variance(D)

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1., 1., 1.], dtype=float16)>

positional min and max

In [ ]:
F = tf.random.uniform(shape = [50, 3])
F

<tf.Tensor: shape=(50, 3), dtype=float32, numpy=
array([[0.83002675, 0.9163941 , 0.01663744],
       [0.534853  , 0.66892326, 0.501971  ],
       [0.46022713, 0.45884466, 0.9301686 ],
       [0.926631  , 0.0718298 , 0.02739346],
       [0.25228715, 0.6477636 , 0.43978786],
       [0.08782995, 0.37806547, 0.6123153 ],
       [0.04042196, 0.17017317, 0.5013938 ],
       [0.88436055, 0.05652916, 0.8595457 ],
       [0.7042047 , 0.34247577, 0.5936111 ],
       [0.87959206, 0.76052594, 0.7123718 ],
       [0.5879581 , 0.99629354, 0.7034793 ],
       [0.10119247, 0.9648411 , 0.5939785 ],
       [0.1541642 , 0.26190186, 0.7834028 ],
       [0.6446941 , 0.2902676 , 0.28010798],
       [0.08578312, 0.43844295, 0.30063093],
       [0.5231545 , 0.61871624, 0.5630834 ],
       [0.12012422, 0.5767088 , 0.44850647],
       [0.11445129, 0.72599685, 0.5446509 ],
       [0.29606426, 0.7088038 , 0.60986495],
       [0.15203118, 0.55962586, 0.82337093],
       [0.19048572, 0.7445451 , 0.30109215],
      

In [ ]:
tf.argmax(F)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([40, 10, 21])>

In [ ]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99629354>

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]